name: Publish extensions to open-vsx.org

on:
  schedule:
    # Run at 07:40 UTC every day.
    - cron:  '40 7 * * *'

jobs:
  publish_extensions:
    name: node publish-extensions
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v1
      with:
        node-version: '12.x'
    - run: npm install
    - run: npm install --global yarn
    - run: node publish-extensions
      env:
        OVSX_PAT: ${{ secrets.OVSX_PAT }}
