name: Publish extensions to open-vsx.org

on:
  schedule:
    # Run at 13:00 UTC every day.
    - cron:  '0 13 * * *'

jobs:
  publish_extensions:
    name: node publish-extensions
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v1
      with:
        node-version: '10.x'
    - uses: actions/setup-python@v2
      with:
        python-version: '3.8'
    - run: npm install
    - run: npm install --global yarn
    - run: node publish-extensions
      env:
        OVSX_PAT: ${{ secrets.OVSX_PAT }}
