name: Publish extensions to open-vsx.org

on:
  schedule:
    # Run at 17:45 UTC every day.
    - cron:  '45 17 * * *'

jobs:
  publish_extensions:
    name: node publish-extensions
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v1
      with:
        node-version: '12.x'
    - run: npm install
    - run: node publish-extensions
